language: python
python: '2.7'

env:
  global:
    - ANSIBLE_VERSION=latest

branches:
  only:
    - master

install:
  - if [ "$ANSIBLE_VERSION" == "latest" ]; then pip install ansible[azure]; else pip
    install ansible[azure]==$ANSIBLE_VERSION; fi
  - ansible --version
  - pip install -I -r ./files/requirements-azure.txt
  - pip freeze
  - git remote set-branches --add origin master
  - git fetch

script:
  - echo 'send notifiication'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
 
