---
- name: Get all supported kubernetes version
  azure_rm_aksversion_facts:
    location: "{{ location }}"
  register: versions

- name: Set kubernetes version
  set_fact:
    kubernetes_version: "{{ versions.azure_aks_versions[-1] }}"
