---
- name: Create vnet
  azure_rm_virtualnetwork:
    resource_group: "{{ resource_group }}"
    name: "{{ name }}{{ rpfx }}"
    address_prefixes_cidr:
      - 10.0.0.0/8

- name: Create subnet
  azure_rm_subnet:
    resource_group: "{{ resource_group }}"
    name: "{{ subnet_name }}"
    address_prefix_cidr: "{{ address }}"
    virtual_network_name: "{{ name }}{{ rpfx }}"
  register: subnet

- name: Set subnet id
  set_fact:
    "{{ parameter }}": "{{ subnet.state.id }}"
