---
- name: Set http_application_routing_bak if httpApplicationRouting exists in profile
  set_fact:
    http_application_routing_bak: "{{ profile.httpApplicationRouting.enabled }}"
  when: "'httpApplicationRouting' in profile"

- name: Set monitoring_bak and workspace_resource_id_bak if omsagent exists in profile
  set_fact:
    monitoring_bak: "{{ profile.omsagent.enabled }}"
    workspace_resource_id_bak: "{{ profile.omsagent.config.logAnalyticsWorkspaceResourceID }}"
  when: "'omsagent' in profile"

- name: Set virtual_node_bak and virtual_node_subnet_id_bak if aciConnector exists in profile
  set_fact:
    virtual_node_bak: "{{ profile.aciConnector.enabled }}"
    virtual_node_subnet_id_bak: "{{ profile.aciConnector.config.SubnetName }}"
  when: "'aciConnector' in profile"
